apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-application-v1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Shenali-SJ/kube-app-tutorial.git
    targetRevision: HEAD
    path: helm/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: argoapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
